version: "3"
services:
  api:
    build:
      context: ./backend
    restart: always
    expose:
      - "3001"
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "Prova1M10"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      # So that our database's state is persisted locally
      - ./database:/docker-entrypoint-initdb.d
      # Where our data will be persisted
      - my-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d Prova1M10"]
      interval: 3s
      timeout: 5s
      retries: 5

# Names our volume
volumes:
  my-db:
